highlighter: pygments
destination: public
paginate: 5
markdown: kramdown
title: "Jesse Read"
name: "Jesse Read"
description: "The musings of a rather nerdy Sith Lord"
url: "https://jesseread.net"
exclude: ["CNAME", "404_template.html", "public", "Rakefile", "_site", "_unpublished", "Gemfile", "Gemfile.lock"]
post:
  template: text.md
  extension: md
feed:
  posts_limit: 20
plugins: [jekyll-paginate, jekyll-sitemap, jekyll-loading-lazy, jekyll-feed, jekyll/footnotes]
